apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v2
  labels:
    app: {{ .Release.Name }}
    version: v2
spec:
  replicas: {{ .Values.v2.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: v2
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          env:
            - name: VERSION
              value: "v2"
            - name: ENABLE_FEATURE_X
              value: "true"
            - name: FEATURE_AWARE
              value: "true"
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}